"""empty message

Revision ID: 28968696ccec
Revises: 393fee889d01
Create Date: 2024-03-26 21:26:47.920612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28968696ccec'
down_revision = '393fee889d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaraunt')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_result', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('test_result')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), nullable=True))

    op.create_table('restaraunt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('adress', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('site', sa.VARCHAR(length=30), nullable=False),
    sa.Column('hours', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('avgPrice', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
